language: android
jdk: oraclejdk8
sudo: false

# Fix License bug: https://github.com/travis-ci/travis-ci/issues/6555#issuecomment-282635361
install:
    - echo y | android update sdk -u -a -t tools
    - echo y | android update sdk -u -a -t platform-tools
    - echo y | android update sdk -u -a -t build-tools-26.0.1
    - echo y | android update sdk -u -a -t android-26
    - echo y | android update sdk -u -a -t sys-img-armeabi-v7a-android-26
    - echo y | android update sdk -u -a -t extra-google-m2repository
    - echo y | android update sdk -u -a -t extra-android-m2repository
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

cache:
    directories:
        - $HOME/.gradle

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    - ./gradlew test
    - ./gradlew connectedAndroidTest
    - ./gradlew check lint assembleDebug --stacktrace